// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: GRPC_Mapper/Map.proto

package GRPCServicePackage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermId        int32                  `protobuf:"varint,1,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	LogId         int32                  `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLogRequest) Reset() {
	*x = RequestLogRequest{}
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLogRequest) ProtoMessage() {}

func (x *RequestLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLogRequest.ProtoReflect.Descriptor instead.
func (*RequestLogRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_Mapper_Map_proto_rawDescGZIP(), []int{0}
}

func (x *RequestLogRequest) GetTermId() int32 {
	if x != nil {
		return x.TermId
	}
	return 0
}

func (x *RequestLogRequest) GetLogId() int32 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type RequestLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLogResponse) Reset() {
	*x = RequestLogResponse{}
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLogResponse) ProtoMessage() {}

func (x *RequestLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLogResponse.ProtoReflect.Descriptor instead.
func (*RequestLogResponse) Descriptor() ([]byte, []int) {
	return file_GRPC_Mapper_Map_proto_rawDescGZIP(), []int{1}
}

func (x *RequestLogResponse) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

type AddLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           []*LogStructure        `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	IsHeartbeat   bool                   `protobuf:"varint,2,opt,name=is_heartbeat,json=isHeartbeat,proto3" json:"is_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLogRequest) Reset() {
	*x = AddLogRequest{}
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLogRequest) ProtoMessage() {}

func (x *AddLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLogRequest.ProtoReflect.Descriptor instead.
func (*AddLogRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_Mapper_Map_proto_rawDescGZIP(), []int{2}
}

func (x *AddLogRequest) GetLog() []*LogStructure {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *AddLogRequest) GetIsHeartbeat() bool {
	if x != nil {
		return x.IsHeartbeat
	}
	return false
}

type LogStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TermId        int32                  `protobuf:"varint,2,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	LogId         int32                  `protobuf:"varint,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStructure) Reset() {
	*x = LogStructure{}
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStructure) ProtoMessage() {}

func (x *LogStructure) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStructure.ProtoReflect.Descriptor instead.
func (*LogStructure) Descriptor() ([]byte, []int) {
	return file_GRPC_Mapper_Map_proto_rawDescGZIP(), []int{3}
}

func (x *LogStructure) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogStructure) GetTermId() int32 {
	if x != nil {
		return x.TermId
	}
	return 0
}

func (x *LogStructure) GetLogId() int32 {
	if x != nil {
		return x.LogId
	}
	return 0
}

type AddLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAnyError    bool                   `protobuf:"varint,1,opt,name=is_any_error,json=isAnyError,proto3" json:"is_any_error,omitempty"`
	ErrorMessages []string               `protobuf:"bytes,2,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLogResponse) Reset() {
	*x = AddLogResponse{}
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLogResponse) ProtoMessage() {}

func (x *AddLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_Mapper_Map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLogResponse.ProtoReflect.Descriptor instead.
func (*AddLogResponse) Descriptor() ([]byte, []int) {
	return file_GRPC_Mapper_Map_proto_rawDescGZIP(), []int{4}
}

func (x *AddLogResponse) GetIsAnyError() bool {
	if x != nil {
		return x.IsAnyError
	}
	return false
}

func (x *AddLogResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

var File_GRPC_Mapper_Map_proto protoreflect.FileDescriptor

const file_GRPC_Mapper_Map_proto_rawDesc = "" +
	"\n" +
	"\x15GRPC_Mapper/Map.proto\x12\x12GRPCServicePackage\"C\n" +
	"\x11RequestLogRequest\x12\x17\n" +
	"\aterm_id\x18\x01 \x01(\x05R\x06termId\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\x05R\x05logId\"(\n" +
	"\x12RequestLogResponse\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\bR\x04vote\"f\n" +
	"\rAddLogRequest\x122\n" +
	"\x03log\x18\x01 \x03(\v2 .GRPCServicePackage.LogStructureR\x03log\x12!\n" +
	"\fis_heartbeat\x18\x02 \x01(\bR\visHeartbeat\"R\n" +
	"\fLogStructure\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\aterm_id\x18\x02 \x01(\x05R\x06termId\x12\x15\n" +
	"\x06log_id\x18\x03 \x01(\x05R\x05logId\"Y\n" +
	"\x0eAddLogResponse\x12 \n" +
	"\fis_any_error\x18\x01 \x01(\bR\n" +
	"isAnyError\x12%\n" +
	"\x0eerror_messages\x18\x02 \x03(\tR\rerrorMessages2\xc5\x01\n" +
	"\n" +
	"RPCService\x12T\n" +
	"\tAppendRPC\x12!.GRPCServicePackage.AddLogRequest\x1a\".GRPCServicePackage.AddLogResponse\"\x00\x12a\n" +
	"\x0eRequestVoteRPC\x12%.GRPCServicePackage.RequestLogRequest\x1a&.GRPCServicePackage.RequestLogResponse\"\x00B)Z'Package/GRPC_Package/GRPCServicePackageb\x06proto3"

var (
	file_GRPC_Mapper_Map_proto_rawDescOnce sync.Once
	file_GRPC_Mapper_Map_proto_rawDescData []byte
)

func file_GRPC_Mapper_Map_proto_rawDescGZIP() []byte {
	file_GRPC_Mapper_Map_proto_rawDescOnce.Do(func() {
		file_GRPC_Mapper_Map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GRPC_Mapper_Map_proto_rawDesc), len(file_GRPC_Mapper_Map_proto_rawDesc)))
	})
	return file_GRPC_Mapper_Map_proto_rawDescData
}

var file_GRPC_Mapper_Map_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_GRPC_Mapper_Map_proto_goTypes = []any{
	(*RequestLogRequest)(nil),  // 0: GRPCServicePackage.RequestLogRequest
	(*RequestLogResponse)(nil), // 1: GRPCServicePackage.RequestLogResponse
	(*AddLogRequest)(nil),      // 2: GRPCServicePackage.AddLogRequest
	(*LogStructure)(nil),       // 3: GRPCServicePackage.LogStructure
	(*AddLogResponse)(nil),     // 4: GRPCServicePackage.AddLogResponse
}
var file_GRPC_Mapper_Map_proto_depIdxs = []int32{
	3, // 0: GRPCServicePackage.AddLogRequest.log:type_name -> GRPCServicePackage.LogStructure
	2, // 1: GRPCServicePackage.RPCService.AppendRPC:input_type -> GRPCServicePackage.AddLogRequest
	0, // 2: GRPCServicePackage.RPCService.RequestVoteRPC:input_type -> GRPCServicePackage.RequestLogRequest
	4, // 3: GRPCServicePackage.RPCService.AppendRPC:output_type -> GRPCServicePackage.AddLogResponse
	1, // 4: GRPCServicePackage.RPCService.RequestVoteRPC:output_type -> GRPCServicePackage.RequestLogResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GRPC_Mapper_Map_proto_init() }
func file_GRPC_Mapper_Map_proto_init() {
	if File_GRPC_Mapper_Map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GRPC_Mapper_Map_proto_rawDesc), len(file_GRPC_Mapper_Map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GRPC_Mapper_Map_proto_goTypes,
		DependencyIndexes: file_GRPC_Mapper_Map_proto_depIdxs,
		MessageInfos:      file_GRPC_Mapper_Map_proto_msgTypes,
	}.Build()
	File_GRPC_Mapper_Map_proto = out.File
	file_GRPC_Mapper_Map_proto_goTypes = nil
	file_GRPC_Mapper_Map_proto_depIdxs = nil
}
