// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: GRPC_Mapper/Map.proto

package GRPCServicePackage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCService_AppendRPC_FullMethodName      = "/GRPCServicePackage.RPCService/AppendRPC"
	RPCService_RequestVoteRPC_FullMethodName = "/GRPCServicePackage.RPCService/RequestVoteRPC"
)

// RPCServiceClient is the client API for RPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Standard RAFT RPC
type RPCServiceClient interface {
	// This is an Append RPC to Propogate logs/HeartBeat Messages from Master to Slave!
	AppendRPC(ctx context.Context, in *AddLogRequest, opts ...grpc.CallOption) (*AddLogResponse, error)
	// This is a Request vote RPC which will be used for leader election
	RequestVoteRPC(ctx context.Context, in *RequestLogRequest, opts ...grpc.CallOption) (*RequestLogResponse, error)
}

type rPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCServiceClient(cc grpc.ClientConnInterface) RPCServiceClient {
	return &rPCServiceClient{cc}
}

func (c *rPCServiceClient) AppendRPC(ctx context.Context, in *AddLogRequest, opts ...grpc.CallOption) (*AddLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLogResponse)
	err := c.cc.Invoke(ctx, RPCService_AppendRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServiceClient) RequestVoteRPC(ctx context.Context, in *RequestLogRequest, opts ...grpc.CallOption) (*RequestLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestLogResponse)
	err := c.cc.Invoke(ctx, RPCService_RequestVoteRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServiceServer is the server API for RPCService service.
// All implementations must embed UnimplementedRPCServiceServer
// for forward compatibility.
//
// Standard RAFT RPC
type RPCServiceServer interface {
	// This is an Append RPC to Propogate logs/HeartBeat Messages from Master to Slave!
	AppendRPC(context.Context, *AddLogRequest) (*AddLogResponse, error)
	// This is a Request vote RPC which will be used for leader election
	RequestVoteRPC(context.Context, *RequestLogRequest) (*RequestLogResponse, error)
	mustEmbedUnimplementedRPCServiceServer()
}

// UnimplementedRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCServiceServer struct{}

func (UnimplementedRPCServiceServer) AppendRPC(context.Context, *AddLogRequest) (*AddLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendRPC not implemented")
}
func (UnimplementedRPCServiceServer) RequestVoteRPC(context.Context, *RequestLogRequest) (*RequestLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVoteRPC not implemented")
}
func (UnimplementedRPCServiceServer) mustEmbedUnimplementedRPCServiceServer() {}
func (UnimplementedRPCServiceServer) testEmbeddedByValue()                    {}

// UnsafeRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServiceServer will
// result in compilation errors.
type UnsafeRPCServiceServer interface {
	mustEmbedUnimplementedRPCServiceServer()
}

func RegisterRPCServiceServer(s grpc.ServiceRegistrar, srv RPCServiceServer) {
	// If the following call panics, it indicates UnimplementedRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCService_ServiceDesc, srv)
}

func _RPCService_AppendRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).AppendRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCService_AppendRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).AppendRPC(ctx, req.(*AddLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCService_RequestVoteRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).RequestVoteRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCService_RequestVoteRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).RequestVoteRPC(ctx, req.(*RequestLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCService_ServiceDesc is the grpc.ServiceDesc for RPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GRPCServicePackage.RPCService",
	HandlerType: (*RPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendRPC",
			Handler:    _RPCService_AppendRPC_Handler,
		},
		{
			MethodName: "RequestVoteRPC",
			Handler:    _RPCService_RequestVoteRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GRPC_Mapper/Map.proto",
}
